<?php

namespace PublicationBundle\Repository;

/**
 * commentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function deletePostCommentaire($idPost)
    {
        $query = $this->getEntityManager()->createQuery(
            'DELETE PublicationBundle:commentaire commentaire
               WHERE commentaire.post = :idPost')
            ->setParameter("idPost", $idPost);

        $query->execute();
    }

}
