<?php

namespace PublicationBundle\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function removePostmedia($idPost)
    {
        $query = $this->getEntityManager()->createQuery(
            'DELETE PublicationBundle:media media
               WHERE media.idpost = :idPost')
            ->setParameter("idPost", $idPost);

        $query->execute();
    }
}
