<?php

namespace PublicationBundle\Repository;

/**
 * PhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotosRepository extends \Doctrine\ORM\EntityRepository
{
}
