<?php

namespace PublicationBundle\Repository;

/**
 * reactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reactionRepository extends \Doctrine\ORM\EntityRepository
{
    public function removePostreaction($idPost)
    {
        $query = $this->getEntityManager()->createQuery(
            'DELETE PublicationBundle:reaction reaction
               WHERE reaction.post = :idPost')
            ->setParameter("idPost", $idPost);

        $query->execute();
    }
}
