<?php

namespace PublicationBundle\Repository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{

    public function removePostVote($idPost)
{
    $query = $this->getEntityManager()->createQuery(
        'DELETE PublicationBundle:Vote Vote
               WHERE Vote.post = :idPost')
        ->setParameter("idPost", $idPost);

    $query->execute();
}
}
